# Generated by Django 6.0.4 on 2026-04-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_academic_year_user_avatar_url_user_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Sinh vien'), ('employer', 'Nha tuyen dung'), ('admin', 'Quan tri vien')], default='student', max_length=10),
        ),
    ]
