# Generated by Django 6.0.4 on 2026-04-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Sinh viên'), ('employer', 'Nhà tuyển dụng'), ('admin', 'Quản trị viên')], default='student', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='skills',
            field=models.TextField(blank=True, help_text='Các kỹ năng, phân tách bằng dấu phẩy'),
        ),
    ]
