# Generated by Django 6.0.4 on 2026-04-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role_alter_user_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/default/'),
        ),
    ]
