# Generated by Django 6.0.1 on 2026-04-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_email_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='company_tax_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='company_website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='employer_verified',
            field=models.BooleanField(default=False),
        ),
    ]
