# Generated by Django 6.0.1 on 2026-05-05 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_district_user_province_user_ward'),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieude', models.CharField(max_length=255)),
                ('hoten', models.CharField(max_length=255)),
                ('diachi', models.CharField(max_length=100)),
                ('muctieu', models.TextField()),
                ('kinhnghiem', models.TextField()),
                ('hocvan', models.TextField()),
                ('ngaytao', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
