# Generated by Django 6.0.1 on 2026-05-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars'),
        ),
    ]
