# Generated by Django 6.0.1 on 2026-05-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_cv_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='sdt',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='hocvan',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='kinhnghiem',
            field=models.TextField(blank=True),
        ),
    ]
