# Generated by Django 6.0.1 on 2026-05-06 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_cv_email_cv_sdt_alter_cv_hocvan_alter_cv_kinhnghiem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='hocvan',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='kinhnghiem',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='ngaytao',
        ),
        migrations.CreateModel(
            name='HocVan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truong', models.CharField(max_length=255)),
                ('nganh', models.CharField(max_length=255)),
                ('batdau', models.CharField(max_length=50)),
                ('kethtuc', models.CharField(max_length=50)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.cv')),
            ],
        ),
        migrations.CreateModel(
            name='KINHNGHIEM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('congty', models.CharField(max_length=255)),
                ('vitri', models.CharField(max_length=255)),
                ('batdau', models.CharField(max_length=50)),
                ('ketthuc', models.TextField()),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.cv')),
            ],
        ),
    ]
