# Generated by Django 6.0.1 on 2026-05-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_cv_hocvan_remove_cv_kinhnghiem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kinhnghiem',
            name='mota',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kinhnghiem',
            name='ketthuc',
            field=models.CharField(max_length=50),
        ),
    ]
