# Generated by Django 6.0.1 on 2026-05-06 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_kinhnghiem_mota_alter_kinhnghiem_ketthuc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hocvan',
            old_name='kethtuc',
            new_name='ketthuc',
        ),
    ]
