# Generated by Django 6.0.1 on 2026-05-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_rename_kethtuc_hocvan_ketthuc'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='kynang',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='muctieu',
            field=models.TextField(blank=True, null=True),
        ),
    ]
