# Generated by Django 6.0.1 on 2026-05-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_cv_kynang_alter_cv_muctieu'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='gioitinh',
            field=models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ')], default='Nam', max_length=10),
        ),
        migrations.AddField(
            model_name='cv',
            name='ngaysinh',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
