# Generated by Django 6.0.1 on 2026-05-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_cv_gioitinh_cv_ngaysinh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='email',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
