# Generated by Django 6.0.4 on 2026-04-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_alter_application_options_application_applied_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Cho duyet'), ('accepted', 'Da chap nhan'), ('rejected', 'Da tu choi'), ('withdrawn', 'Da rut don')], default='pending', max_length=20),
        ),
    ]
