# Generated by Django 6.0.4 on 2026-04-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ duyệt'), ('accepted', 'Đã chấp nhận'), ('rejected', 'Đã từ chối'), ('withdrawn', 'Đã rút đơn')], default='pending', max_length=20),
        ),
    ]
