# Generated by Django 6.0.4 on 2026-04-09 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_application_cv_file_application_expected_salary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='estimated_days',
        ),
        migrations.AddField(
            model_name='application',
            name='available_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
