# Generated by Django 6.0.4 on 2026-04-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_remove_application_estimated_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='candidate_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='application',
            name='candidate_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
