# Generated by Django 6.0.4 on 2026-04-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_options_job_budget_max_job_budget_min_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('open', 'Dang tuyen'), ('in_progress', 'Dang thuc hien'), ('completed', 'Da hoan thanh'), ('cancelled', 'Da huy')], default='open', max_length=20),
        ),
    ]
