# Generated by Django 6.0.4 on 2026-04-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='required_skills',
            field=models.TextField(blank=True, help_text='Các kỹ năng yêu cầu, phân tách bằng dấu phẩy'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('open', 'Đang tuyển'), ('in_progress', 'Đang thực hiện'), ('completed', 'Đã hoàn thành'), ('cancelled', 'Đã hủy')], default='open', max_length=20),
        ),
    ]
