# Generated by Django 6.0.4 on 2026-04-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_job_required_skills_alter_job_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Linh vuc',
                'verbose_name_plural': 'Linh vuc',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='job',
            name='budget_max',
        ),
        migrations.RemoveField(
            model_name='job',
            name='budget_min',
        ),
        migrations.RemoveField(
            model_name='job',
            name='is_remote',
        ),
        migrations.AddField(
            model_name='job',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='job',
            name='employment_type',
            field=models.CharField(choices=[('project', 'Theo du an'), ('part_time', 'Ban thoi gian'), ('full_time', 'Toan thoi gian'), ('internship', 'Thuc tap')], default='project', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='experience_level',
            field=models.CharField(choices=[('none', 'Khong yeu cau'), ('intern', 'Thuc tap sinh'), ('junior', 'Junior'), ('mid', 'Middle'), ('senior', 'Senior')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_type',
            field=models.CharField(choices=[('negotiable', 'Thoa thuan'), ('range', 'Khoang luong'), ('fixed', 'Luong co dinh')], default='negotiable', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='vacancies',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='job',
            name='work_mode',
            field=models.CharField(choices=[('remote', 'Lam tu xa'), ('onsite', 'Lam tai van phong'), ('hybrid', 'Linh hoat (Hybrid)')], default='remote', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='required_skills',
            field=models.TextField(blank=True, help_text='Cac ky nang yeu cau, phan tach bang dau phay'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('open', 'Dang tuyen'), ('in_progress', 'Dang thuc hien'), ('completed', 'Da hoan thanh'), ('cancelled', 'Da huy')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='jobs.jobcategory'),
        ),
    ]
