# Generated by Django 6.0.4 on 2026-04-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_jobcategory_remove_job_budget_max_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobcategory',
            options={'ordering': ['name'], 'verbose_name': 'Lĩnh vực', 'verbose_name_plural': 'Lĩnh vực'},
        ),
        migrations.AlterField(
            model_name='job',
            name='employment_type',
            field=models.CharField(choices=[('project', 'Theo dự án'), ('part_time', 'Bán thời gian'), ('full_time', 'Toàn thời gian'), ('internship', 'Thực tập')], default='project', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience_level',
            field=models.CharField(choices=[('none', 'Không yêu cầu'), ('intern', 'Thực tập sinh'), ('junior', 'Junior'), ('mid', 'Middle'), ('senior', 'Senior')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='required_skills',
            field=models.TextField(blank=True, help_text='Các kỹ năng yêu cầu, phân tách bằng dấu phẩy'),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_type',
            field=models.CharField(choices=[('negotiable', 'Thỏa thuận'), ('range', 'Khoảng lương'), ('fixed', 'Lương cố định')], default='negotiable', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('open', 'Đang tuyển'), ('in_progress', 'Đang thực hiện'), ('completed', 'Đã hoàn thành'), ('cancelled', 'Đã hủy')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='work_mode',
            field=models.CharField(choices=[('remote', 'Làm từ xa'), ('onsite', 'Làm tại văn phòng'), ('hybrid', 'Linh hoạt (Hybrid)')], default='remote', max_length=20),
        ),
    ]
