# Generated by Django 6.0.4 on 2026-04-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_seed_default_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='experience_level',
            field=models.CharField(choices=[('0_year', 'Không kinh nghiệm'), ('1_year', '1 năm'), ('2_year', '2 năm'), ('3_year', '3 năm'), ('4_year', '4 năm'), ('5_plus', 'Từ 5 năm trở lên')], default='0_year', max_length=20),
        ),
    ]
