# Generated by Django 6.0.4 on 2026-04-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_alter_job_experience_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='experience_level',
            field=models.CharField(choices=[('0_year', 'Không kinh nghiệm'), ('1_year', '1 năm'), ('2_year', '2 năm'), ('3_year', '3 năm'), ('5_plus', 'Trên 4 năm')], default='0_year', max_length=20),
        ),
    ]
